### PR TITLE
Webrtc stuff

### PR DESCRIPTION
**Pull request by Kaweees**
- Added peer-to-peer video streaming capabilities via a serverless signaling server
> [!NOTE]
>  Make sure to add firebase env vars to .env.local inside /nextjs

To do:
- Implement messagining

### CODE REVIEW

**Comment by ZealSV** [comment]
Great work Miguel and Hannah, really clutch with the research showing fruition with video and chat working.

**Comment by hanmosh** [comment]
Good work Miguel, just cleaned up some of the type errors for the deployment!

**Comment by sanjanachecker** [comment]
Great work Miguel!

**Review by ObjectJosh — COMMENTED** [review]
Good work, Miguel. Thanks for implementing sockets & webrtc, I'll make sure everyone updates their .envs with the new variables

**Pull request merged**
