### PR TITLE
Protected routes, init mongo, kinde auth funcs

### PR DESCRIPTION
**Pull request by ObjectJosh**
- Added protected routes (settings and chat page)
- Initialized and dbConnect to MongoDB, init schema user - email, first name, last name
- Uses kinde auth functions rather than kinde links
    - logout btn properly logs out, sign in uses kinde log in
> [!NOTE]
>  Make sure to add env vars to .env.local inside /nextjs

To do:
- [x] Doesn't use our custom sign in page yet, see task #16 
- [x] custom pages bc we want to validate email & also no context switch when it goes to select major / hobby

### CODE REVIEW

**Comment by ZealSV** [comment]
Took around 10 hours

**Comment by sanjanachecker** [comment]
Good job Josh and Muzart!

**Comment by hanmosh** [comment]
Looks good to me! No further comments.

**Comment by ZealSV** [comment]
> Good job Josh and Muzart!

Thank you Sanjana!

**Comment by ZealSV** [comment]
> Looks good to me! No further comments.

Great! Backend is looking good

**Comment by ObjectJosh** [comment]
> Good job Josh and Muzart!
> Looks good to me! No further comments.

Thanks all 👍

**Pull request merged**
