### PR TITLE
Protected routes, init mongo, kinde auth funcs

### PR DESCRIPTION
**Pull request by ObjectJosh**
- Added protected routes (settings and chat page)
- Initialized and dbConnect to MongoDB, init schema user - email, first name, last name
- Uses kinde auth functions rather than kinde links
    - logout btn properly logs out, sign in uses kinde log in
> [!NOTE]
>  Make sure to add env vars to .env.local inside /nextjs

To do:
- Doesn't use our custom sign in page yet, see task #16 
- custom pages bc we want to validate email & also no context switch when it goes to select major / hobby

### CODE REVIEW

**Comment by ZealSV** [comment]
Took around 10 hours total

**Comment by hanmosh** [comment]
Good work! No comments from me.

**Comment by sanjanachecker** [comment]
Good job! No further comments.

**Comment by ZealSV** [comment]
> Good work! No comments from me.

Thank you Hannah!

**Comment by ZealSV** [comment]
> Good job! No further comments.

Thanks :)

**Pull request closed without merging**
