### PR TITLE
22 editing account settings frontend

### PR DESCRIPTION
**Pull request by sanjanachecker**
Fixed edit acct settings:
- removed pencil from email
- made name editable
- dropdowns for major and year
- navigation to select tags page when editing tags

### CODE REVIEW

**Review by hanmosh — APPROVED** [review]
Looks great! I just added a save button and merged in the main code.

**Comment by ZealSV** [comment]
Good work! Account editing feature works and frontend looks like just like the design.

**Comment by sanjanachecker** [comment]
> Looks great! I just added a save button and merged in the main code.
Thanks for the help Hannah!

**Comment by sanjanachecker** [comment]
> Good work! Account editing feature works and frontend looks like just like the design.

Thank you Muzart!

**Review by ObjectJosh — COMMENTED** [review]
Great work, thanks for implementing the tags, majors, & settings page!

**Pull request merged**
