### PR TITLE
Banned page routing

### PR DESCRIPTION
**Pull request by ZealSV**

### CODE REVIEW

**Comment by sanjanachecker** [comment]
Good work Muzart! No comments.

**Comment by ZealSV** [comment]
Took around 2 hours

**Comment by ZealSV** [comment]
> Good work Muzart! No comments.

Thanks Sanjana!

**Comment by hanmosh** [comment]
Wow! Amazing work you really outdid yourself with this one. Code is phenomenal, file organization is perfect, couldn't have been better. I am very impressed.

**Comment by ZealSV** [comment]
> Wow! Amazing work you really outdid yourself with this one. Code is phenomenal, file organization is perfect, couldn't have been better. I am very impressed.

Why thank you, I appreciate it. I tried to make it simple so that it would be easy to understand

**Pull request merged**
