### PR TITLE
26 clean up report feature

### PR DESCRIPTION
**Pull request by sanjanachecker**
fixed UI
added mandatory reason for reporting

### CODE REVIEW

**Comment by ZealSV** [comment]
Good work! Report looks clean and matches new design.

**Comment by hanmosh** [comment]
Looks great! Thanks!

**Comment by sanjanachecker** [comment]
> Good work! Report looks clean and matches new design.

Thank you!

**Comment by sanjanachecker** [comment]
> Looks great! Thanks!

You're welcome!

**Review by ObjectJosh — COMMENTED** [review]
Changes look good, thanks 💯

**Pull request merged**
